// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __Test_hh__
#define __Test_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_Test
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_Test
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_Test
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE Test

_CORBA_MODULE_BEG

  struct Message {
    typedef _CORBA_ConstrType_Variable_Var<Message> _var_type;

    
    ::CORBA::String_member title;

    ::CORBA::String_member author;

    ::CORBA::String_member date;

    ::CORBA::String_member body;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef Message::_var_type Message_var;

  typedef _CORBA_ConstrType_Variable_OUT_arg< Message,Message_var > Message_out;

#ifndef __Test_mForum__
#define __Test_mForum__

  class Forum;
  class _objref_Forum;
  class _impl_Forum;
  
  typedef _objref_Forum* Forum_ptr;
  typedef Forum_ptr ForumRef;

  class Forum_Helper {
  public:
    typedef Forum_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Forum, Forum_Helper> Forum_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Forum,Forum_Helper > Forum_out;

#endif

  // interface Forum
  class Forum {
  public:
    // Declarations for this interface type.
    typedef Forum_ptr _ptr_type;
    typedef Forum_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Forum :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    ::CORBA::Boolean postMessage(const ::Test::Message& m);
    Message* getMessage(const char* title);
    ::CORBA::Boolean removeMessage(const char* title);
    char* theme();
    char* moderator();

    inline _objref_Forum()  { _PR_setobj(0); }  // nil
    _objref_Forum(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Forum();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Forum(const _objref_Forum&);
    _objref_Forum& operator = (const _objref_Forum&);
    // not implemented

    friend class Forum;
  };

  class _pof_Forum : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Forum() : _OMNI_NS(proxyObjectFactory)(Forum::_PD_repoId) {}
    virtual ~_pof_Forum();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Forum :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Forum();

    virtual ::CORBA::Boolean postMessage(const ::Test::Message& m) = 0;
    virtual Message* getMessage(const char* title) = 0;
    virtual ::CORBA::Boolean removeMessage(const char* title) = 0;
    virtual char* theme() = 0;
    virtual char* moderator() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_Test
_CORBA_MODULE_BEG

  class Forum :
    public virtual Test::_impl_Forum,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Forum();

    inline ::Test::Forum_ptr _this() {
      return (::Test::Forum_ptr) _do_this(::Test::Forum::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_Test
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
Test::Forum::_marshalObjRef(::Test::Forum_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_Test
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_Test
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_Test
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_Test
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_Test
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_Test
#endif

#endif  // __Test_hh__

